version: "3.7"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mynetwork

  api:
    container_name: api
    build: ./api
    env_file:
      - ./api/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - frontend-volume:/app
    ports:
      - "3000:3000" # Porta externa mapeada para o Next.js
    networks:
      - mynetwork

volumes:
  mongodb_data_container:
  frontend-volume: # Definindo o volume para o frontend

networks:
  mynetwork:
    driver: bridge
